zombie-drops:
  - "IRON_INGOT"
  - "GOLD_INGOT"
  - "DIAMOND"
  - "EMERALD"
  - "DEAD_BUSH"
  - "BREAD"
  - "STICK"
  - "LEATHER"
  - "BONE"
  - "LEATHER_HELMET"
  - "LEATHER_CHESTPLATE"
  - "LEATHER_LEGGINGS"
  - "LEATHER_BOOTS"