worldname: "world" # Name of the world to spawn zombies in
max-zombies: 50 # Maximum amount of zombies to spawn
radius: 100 # Radius around the player to spawn zombies
zombie-drops:
  - "IRON_INGOT"
  - "GOLD_INGOT"
  - "DIAMOND"
  - "EMERALD"
  - "DEAD_BUSH"
  - "BREAD"
  - "STICK"
  - "LEATHER"
  - "BONE"