name: servercore_za
version: '1.0-SNAPSHOT'
main: net.thedawnph.servercore_za.Servercore_za
api-version: '1.20'
load: STARTUP
authors: [ princepines ]
description: Server Core for TheDawnPH Zombie Apocalypse
website: https://thedawnph.net
depend: [ZombieApocalypse]
commands:
  coreinfo:
    description: Server Core for TheDawnPH Zombie Apocalypse
    usage: /coreinfo
    permission: servercore_za.command
    permission-message: You do not have permission to use this command.
permissions:
  servercore_za.command:
    description: Permission to use Server Core for TheDawnPH Zombie Apocalypse
    default: op
